I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/phase_4_dinner.rpy", line 772, in script
    if currentCompliance < highComplBR:
  File "game/phase_4_dinner.rpy", line 772, in <module>
    if currentCompliance < highComplBR:
NameError: name 'currentCompliance' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/phase_4_dinner.rpy", line 772, in script
    if currentCompliance < highComplBR:
  File "renpy/ast.py", line 1898, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/phase_4_dinner.rpy", line 772, in <module>
    if currentCompliance < highComplBR:
NameError: name 'currentCompliance' is not defined

Windows-10-10.0.22000
Ren'Py 7.4.9.2142
Make Yourself at Home 1.0
Mon Mar 28 21:23:10 2022
